Create retour-paris-web-flo.md
la-veilleuse/la-veilleuse pull request #20
Opened 2016-11-02 09:03 UTC by FBerthelot

2016-11-04 16:45 UTC, FBerthelot commented on src/articles/retour-paris-web-flo.md
> +### Le bon coin, les coulisses d'une refonte graphique
Leboncoin

2016-11-16 12:24 UTC, jgrenat requested changes

2016-11-16 12:24 UTC, jgrenat commented on src/articles/retour-paris-web-flo.md
> +[Thibault Jouannic](https://twitter.com/thibaultj), dans sa [conférence de sensibilisation](https://www.miximum.fr/blog/conf-pw-2017/), nous invite à nous poser les bonnes questions. Pour lui – et je
informations aussi "anodines"

2016-11-16 12:24 UTC, jgrenat commented on src/articles/retour-paris-web-flo.md
> +[Thibault Jouannic](https://twitter.com/thibaultj), dans sa [conférence de sensibilisation](https://www.miximum.fr/blog/conf-pw-2017/), nous invite à nous poser les bonnes questions. Pour lui – et je
IMO I find that an address seems to be a very sensitive piece of information, even without this context!

2016-11-16 12:24 UTC, jgrenat commented on src/articles/retour-paris-web-flo.md
> +Je peux vous dire qu'en plus de la simple traduction, il faut parfois pouvoir changer les paramètres de validation d'un formulaire en fonction de la langue. En effet, certain prénom peuvent être codé
certains prénoms

2016-11-16 12:24 UTC, jgrenat commented on src/articles/retour-paris-web-flo.md
> +Je peux vous dire qu'en plus de la simple traduction, il faut parfois pouvoir changer les paramètres de validation d'un formulaire en fonction de la langue. En effet, certain prénom peuvent être codé
un ou deux

2016-11-16 12:24 UTC, jgrenat commented on src/articles/retour-paris-web-flo.md
> +Idéalement, la disposition des éléments dans la page pensée de façon à permettre une lecture aisée quel que soit le sens de lecture. Le site marocain de [2M](http://www.2m.ma/) en est un bon exemple
doit être pensée

2016-11-16 12:24 UTC, jgrenat commented on src/articles/retour-paris-web-flo.md
> +L'ancien CTO de eTF1 - étant actuellement en mission là-bas, j'ai découvert qu'il s'agit du prédecesseur de mon patron actuel en écrivant cet article - nous a permis dans une première partie d'effleu
Stop telling your life!

2016-11-16 12:24 UTC, jgrenat commented on src/articles/retour-paris-web-flo.md
> +L'ancien CTO de eTF1 - étant actuellement en mission là-bas, j'ai découvert qu'il s'agit du prédecesseur de mon patron actuel en écrivant cet article - nous a permis dans une première partie d'effleu
des connaissances sur la blockchain étant nécessaires avant de poursuivre.

2016-11-16 12:24 UTC, jgrenat commented on src/articles/retour-paris-web-flo.md
> +La blockchain, c'est lent. En effet, avant qu'un nouveau document rentre dans le *système* il faut 30 secondes pour le Bitcoin , des fois un mois pour d'autres systèmes. Une fois le bloc dans le *sys
Bitcoin,

2016-11-16 12:24 UTC, jgrenat commented on src/articles/retour-paris-web-flo.md
> +La blockchain ne s'applique pas à tout non plus, si l'on vous parle de blockchain en réseau privé, où est l'intérêt ? La blockchain c'est parfait pour obtenir des certificats signés et approuvés par
quand personne ne se fait confiance

2016-11-16 12:24 UTC, jgrenat commented on src/articles/retour-paris-web-flo.md
> +La blockchain ne s'applique pas à tout non plus, si l'on vous parle de blockchain en réseau privé, où est l'intérêt ? La blockchain c'est parfait pour obtenir des certificats signés et approuvés par
m'a permis d'avoir ce recul

2016-11-16 12:24 UTC, jgrenat commented on src/articles/retour-paris-web-flo.md
> +Cette histoire montre que tout est parti d'une cryptoparty - ou chiffro-fête en français - à Hawaii. Les Cryptoparty sont des sortes de Meetup ouverts à tous – le but étant justement de sensibiliser
Les cryptoparties

2016-11-16 12:24 UTC, jgrenat commented on src/articles/retour-paris-web-flo.md
> +Conférence que je qualifierais comme intéressante et dérangeante tout à la fois. Je m'explique : la première partie était très bien et [Avi Itzkovitch](https://twitter.com/xgmedia) nous a expliqué po
que je qualifierais d'intéressante

2016-11-16 12:24 UTC, jgrenat commented on src/articles/retour-paris-web-flo.md
> +Excellente conférence, une des plus technique que j'aie vu durant ces deux jours. Pour faire très simple, [Gaël Poupard](https://twitter.com/ffoodd_fr?lang=fr) nous a expliqué [pourquoi les intégrate
une des plus techniques

2016-11-16 12:24 UTC, jgrenat commented on src/articles/retour-paris-web-flo.md
> +Cette conférence a permis de renforcer mon envie de m'investir d'avantage dans l'agence numérique [AYA](www.aya-experience.com) qui est en train d'être montée au sein de Zenika, car j'en ai vraiment
"j'en ai marre" => Oooooh poor boy! Stop telling your life!

2016-11-16 12:24 UTC, jgrenat commented on src/articles/retour-paris-web-flo.md
> +Oui, mais ma mère - ou toute autre personne non technique - ne pourrait pas éditer une page sur mon site statique, elle serait perdue. C'est là que [la présentation](http://frank.taillandier.me/prese
Why `JAMStack` ?

2016-11-16 12:24 UTC, jgrenat commented on src/articles/retour-paris-web-flo.md
> +Pour vous dépeindre cette conférence, je vous demande de faire appel à votre mémoire et à votre imagination. Imaginez une documentation W3C de 300 pages ; si vous ne voyez pas imaginez une spécificat
une démonstration sur dix

2016-11-16 12:24 UTC, jgrenat commented on src/articles/retour-paris-web-flo.md
> +Ils ont d’abord fait une revue des nouvelles API disponibles et moi qui adore toutes ces API, qui étendent les possibilités des applications web, j'ai simplement adoré. Au programme, une api de vibra
Stop telling your fucking life!

2016-11-16 12:24 UTC, jgrenat commented on src/articles/retour-paris-web-flo.md
> +Pour mener à bien cette refonte, j'ai aimé bien des aspects : les tests utilisateurs en conditions réelles (beta publique), la livraison par lot en production (encore actuellement tout le site respon
par lots

2016-11-16 16:24 UTC, merged